<?php
/**
 * Test Link Generation
 * 
 * This script tests the link generation and access URL functionality
 */

// Define constant to prevent direct access to included files
define('ACCESS_CONTROL', true);

// Include utility functions
require_once __DIR__ . '/api/utils/storage.php';
require_once __DIR__ . '/api/utils/security.php';
require_once __DIR__ . '/api/utils/link_service.php';

// Output header
echo "<!DOCTYPE html>
<html>
<head>
    <title>Test Link Generation</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        h1, h2, h3 { color: #333; }
        .success { color: green; }
        .error { color: red; }
        .section { margin-bottom: 20px; padding: 10px; border: 1px solid #ddd; }
        pre { background: #f5f5f5; padding: 10px; overflow: auto; }
        .button { 
            display: inline-block; 
            padding: 10px 15px; 
            background: #4a6fa5; 
            color: white; 
            text-decoration: none; 
            border-radius: 4px;
            margin: 10px 0;
        }
    </style>
</head>
<body>
    <h1>Test Link Generation</h1>";

// Get action from query parameter
$action = $_GET['action'] ?? '';

// Generate a test link
if ($action === 'generate') {
    echo "<div class='section'>";
    echo "<h2>Generating Test Link</h2>";
    
    // Get games
    $games = getGames();
    
    if (empty($games['games'])) {
        echo "<p class='error'>No games found in games.json</p>";
    } else {
        // Use the first game
        $gameId = $games['games'][0]['id'];
        
        // Generate link
        $result = generateLink([$gameId], 3600, 1, 'Test link generated by test script');
        
        if ($result['success']) {
            $link = $result['link'];
            
            // Get base URL
            $baseUrl = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST'];
            $accessUrl = $baseUrl . '/Link-Issuance-System/direct-access.php?token=' . $link['token'];
            
            echo "<p class='success'>Link generated successfully!</p>";
            echo "<h3>Link Details</h3>";
            echo "<pre>" . htmlspecialchars(print_r($link, true)) . "</pre>";
            
            echo "<h3>Access URL</h3>";
            echo "<p><a href='" . htmlspecialchars($accessUrl) . "' target='_blank'>" . htmlspecialchars($accessUrl) . "</a></p>";
            
            echo "<h3>Test Access URL</h3>";
            echo "<p><a href='check_access_url.php?token=" . htmlspecialchars($link['token']) . "' class='button'>Test Access URL</a></p>";
        } else {
            echo "<p class='error'>Failed to generate link: " . htmlspecialchars($result['message']) . "</p>";
        }
    }
    
    echo "</div>";
}

// Check links.json
echo "<div class='section'>";
echo "<h2>Current Links</h2>";

$links = getLinks();

if (empty($links)) {
    echo "<p>No links found in links.json</p>";
} else {
    echo "<p>" . count($links) . " links found in links.json</p>";
    
    echo "<table border='1' cellpadding='5' cellspacing='0' style='border-collapse: collapse;'>";
    echo "<tr><th>ID</th><th>Token</th><th>Game IDs</th><th>Created</th><th>Actions</th></tr>";
    
    foreach ($links as $link) {
        $baseUrl = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST'];
        $accessUrl = $baseUrl . '/Link-Issuance-System/direct-access.php?token=' . $link['token'];
        
        echo "<tr>";
        echo "<td>" . htmlspecialchars($link['id']) . "</td>";
        echo "<td>" . htmlspecialchars($link['token']) . "</td>";
        echo "<td>" . htmlspecialchars(implode(', ', $link['game_ids'])) . "</td>";
        echo "<td>" . date('Y-m-d H:i:s', $link['created_at']) . "</td>";
        echo "<td>";
        echo "<a href='" . htmlspecialchars($accessUrl) . "' target='_blank' class='button'>Access</a> ";
        echo "<a href='check_access_url.php?token=" . htmlspecialchars($link['token']) . "' class='button'>Test</a>";
        echo "</td>";
        echo "</tr>";
    }
    
    echo "</table>";
}

echo "</div>";

// Generate button
echo "<div class='section'>";
echo "<h2>Actions</h2>";
echo "<p><a href='test_link_generation.php?action=generate' class='button'>Generate Test Link</a></p>";
echo "</div>";

// Server information
echo "<div class='section'>";
echo "<h2>Server Information</h2>";
echo "<p>PHP Version: " . phpversion() . "</p>";
echo "<p>Server Software: " . ($_SERVER['SERVER_SOFTWARE'] ?? 'Unknown') . "</p>";
echo "<p>Document Root: " . ($_SERVER['DOCUMENT_ROOT'] ?? 'Unknown') . "</p>";
echo "<p>Current Script: " . __FILE__ . "</p>";
echo "<p>HTTP_HOST: " . ($_SERVER['HTTP_HOST'] ?? 'Unknown') . "</p>";
echo "<p>REQUEST_URI: " . ($_SERVER['REQUEST_URI'] ?? 'Unknown') . "</p>";
echo "</div>";

echo "</body></html>";
